version: "3"
services:
  site:
    # environment:
    #   - COMPOSE_CONVERT_WINDOWS_PATHS=1
    #   - FORCE_APK_INSTALL=true
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
